# -*- coding: utf-8 -*-

# SIGNAL
EXIT_MIDWAY = 1
MAIN_ASYNC_TASK_SYMBOL = 1

# DEFAULT ARGUMENTS
ASYNC_TASKS_MAINTAIN = -1
INSPECT_INTERVAL = 2.
FETCH_FAILURE_TRIES = 10

# OUT FILES
CONCAT_FILE_CONTAINER = "CONCAT.txt"
CONCAT_FILE_TXT = "CONCATENAR.txt"
CONCAT_FILE_BAT = "CONCATENAR.bat"
CONCAT_OBJECT_NAME = "VIDEO"

# SPECIAL CHARACTERS
FILE_SC = '\\/:*?"<>|'
